name: proyectos_cliente
description: "Aplicacion para Concurso de proyectos de EPIS - Cliente"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  file_picker: ^8.0.6
  url_launcher: ^6.3.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1
  image_picker: ^1.1.2

  # The following adds the Cupertino Icons font to your application.
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
