name: proyectos_cliente
description: "Aplicacion para Concurso de proyectos de EPIS - Cliente"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  image_picker: ^1.1.2 # <--- AÑADIDO
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
